### ISSUE TITLE
io.jxcore.node/ directory duplicate

### ISSUE THREAD

**Issue by cdynak** [jxcore/jxc#1]
after using `jxc install` jxcore cordova plugin is properly added, but `io.jxcore.node/` directory still exists in  project root. for me it should be deleted in the end because it is 1:1 duplicate: `$diff -r io.jxcore.node/ plugins/io.jxcore.node/` confirms that.

anyway, is there no possibility to just host jxcore cordova plugin on npm? i know that it is quite large, but it could very increase jxcore popularity, especially when it will be tagged `ecosystem:cordova`.

**Comment by ktrzeciaknubisa** [comment]
Yeap, the folders are same, however leaving it under `io.jxcore.node` allows you to re-add the plugin without downloading (if you'll ever have this kind of need). You may be right though, that deleting should be done by default, and we may add some switch, e.g. `--no-remove` for other scenarios.

**Comment by ktrzeciaknubisa** [comment]
> anyway, is there no possibility to just host jxcore cordova plugin on npm? i know that it is quite large, but it could very increase jxcore popularity, especially when it will be tagged ecosystem:cordova.

@obastemur what do you think about this?

**Comment by cdynak** [comment]
exactly, the best idea is disabling it by default and adding flag `--no-remove` or something similar that makes possible downloading plugin outside of cordova project root. the only question now is: it should be done twice for `lib/commands/*` or once in `bin/jxc.bin.js`?

**Comment by ktrzeciaknubisa** [comment]
The master branch has an updates now. The `io.jxcore.node` is removed by default.

Of someone wants to keep downloaded packages in cache, there are some ways for this: [caching-downloaded-files](https://github.com/ktrzeciaknubisa/jxc#caching-downloaded-files).

**Comment by cdynak** [comment]
thank you! idea of caching is nice and it had been well implemented.
