### ISSUE TITLE
The installation may sometimes fail in certain environments

### ISSUE THREAD

**Issue by vjrantal** [jxcore/jxc#6]
We have a CI environment where we see that the installation (or download) fails.

The root cause is unknown and I haven't been able to reproduce locally. An example failure output at https://github.com/ThaliTester/TestResults/blob/5585889128538fc_Test_jxc_download__vjrantal/build.md .

**Comment by ktrzeciaknubisa** [comment]
That part should be already improved in jxc starting from 1.0.12. Thank you @vjrantal .
